version: '3'
services:
  mongo:
    image: mongo
    restart: always

  server:
    build: ./packages/server
    restart: always
    depends_on:
      - mongo
    environment:
      - SENTRY_DSN=
    ports:
    - "3002:3000"